/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia1astridperez;

import javax.swing.JOptionPane;

/**
 *
 * @author Astrid
 */
public class jCalculo extends javax.swing.JFrame {

    /**
     * Creates new form jCalculo
     */
    public jCalculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTema = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlCarrera = new javax.swing.JLabel();
        jlCiclo = new javax.swing.JLabel();
        jlCum = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfNombre = new javax.swing.JTextField();
        cbCarrera = new javax.swing.JComboBox<>();
        cbCiclo = new javax.swing.JComboBox<>();
        cbMateria1 = new javax.swing.JComboBox<>();
        cbMateria2 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        cbMateria5 = new javax.swing.JComboBox<>();
        jlMateria = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbUV1 = new javax.swing.JComboBox<>();
        cbUV2 = new javax.swing.JComboBox<>();
        cbUV3 = new javax.swing.JComboBox<>();
        cbUV4 = new javax.swing.JComboBox<>();
        cbUV5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfNota1 = new javax.swing.JTextField();
        tfNota2 = new javax.swing.JTextField();
        tfNota3 = new javax.swing.JTextField();
        tfNota4 = new javax.swing.JTextField();
        tfNota5 = new javax.swing.JTextField();
        lbEstado1 = new javax.swing.JLabel();
        lbEstado3 = new javax.swing.JLabel();
        lbEstado2 = new javax.swing.JLabel();
        lbEstado5 = new javax.swing.JLabel();
        lbEstado4 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jlCum1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlNombre1 = new javax.swing.JLabel();
        jlNombre2 = new javax.swing.JLabel();
        jlCarrera1 = new javax.swing.JLabel();
        jlCarrera2 = new javax.swing.JLabel();
        jlCarrera3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 250));
        setMaximumSize(new java.awt.Dimension(675, 500));
        setPreferredSize(new java.awt.Dimension(675, 500));

        jLabelTema.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTema.setText("Control de Notas");

        jlNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlNombre.setText("Nombre:");

        jlCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCarrera.setText("Carrera:");

        jlCiclo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCiclo.setText("Ciclo:");

        jlCum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCum.setText("CUM:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Ingenieria en Sistemas", "Ingenieria Electrica", "Ingeniria Industrial", "Ingenieria en Agronegocios" }));

        cbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "01", "02" }));

        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Bases de Datos ll", "Desarrollo de Softwae l", "Investigacion de Operaciones l", "Legislacion Aplicada a la Empresa", "Electronica" }));

        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Bases de Datos ll", "Desarrollo de Softwae l", "Investigacion de Operaciones l", "Legislacion Aplicada a la Empresa", "Electronica" }));

        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Bases de Datos ll", "Desarrollo de Softwae l", "Investigacion de Operaciones l", "Legislacion Aplicada a la Empresa", "Electronica" }));
        cbMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateria3ActionPerformed(evt);
            }
        });

        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Bases de Datos ll", "Desarrollo de Softwae l", "Investigacion de Operaciones l", "Legislacion Aplicada a la Empresa", "Electronica" }));

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Bases de Datos ll", "Desarrollo de Softwae l", "Investigacion de Operaciones l", "Legislacion Aplicada a la Empresa", "Electronica" }));

        jlMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlMateria.setText("Materia");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("UV");

        cbUV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));

        cbUV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));

        cbUV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));

        cbUV4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));

        cbUV5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nota");

        tfNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota4ActionPerformed(evt);
            }
        });

        lbEstado1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEstado1.setText("Estado");

        lbEstado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEstado3.setText("Estado");

        lbEstado2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEstado2.setText("Estado");

        lbEstado5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEstado5.setText("Estado");

        lbEstado4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEstado4.setText("Estado");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jlCum1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCum1.setText("0.0");

        jPanel2.setBackground(new java.awt.Color(234, 252, 252));

        jlNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlNombre1.setText("Calculo Exitoso");

        jlNombre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlNombre2.setText("Estudiante");

        jlCarrera1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCarrera1.setText("de la Carrera ");

        jlCarrera2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCarrera2.setText("Carrera");

        jlCarrera3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCarrera3.setText("Estado Actual es #");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nota");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Materias Reprobadas su CUM es");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Materias Aprobadas y #");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nota");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Nota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCarrera1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCarrera2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlCarrera3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre1)
                    .addComponent(jlNombre2)
                    .addComponent(jlCarrera1)
                    .addComponent(jlCarrera2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCarrera3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlMateria)
                                .addGap(105, 105, 105))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(btnCalcular)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbEstado5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbEstado3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbEstado4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbEstado2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbEstado1)))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jlCum1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jlNombre)
                                .addGap(88, 88, 88)
                                .addComponent(jlCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jlCum)
                                .addGap(91, 91, 91))))))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTema)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelTema)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jlCarrera)
                    .addComponent(jlCiclo)
                    .addComponent(jlCum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCum1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMateria)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstado2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbEstado1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado3)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado4)
                    .addComponent(btnCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado5))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void cbMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateria3ActionPerformed

    private void tfNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota4ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
        String cicloActual = " ";
        String Carrera = " ";
    
        String carreraSelec = (String)this.cbCarrera.getSelectedItem();
        String cicloSeleccionado = (String) cbCiclo.getSelectedItem();
        
        // Validamos por defecto
        if ("-Seleccione-".equals(carreraSelec)) {
            JOptionPane.showMessageDialog(this, "Seleccione una Carrera.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Sale del programa si no se ha seleccionado una Carrera válida
        }
        
        //Validamos el nombre
        if (tfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor en el campo Nombre.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Sale del programa si el campo está vacío
        }
        
        /*Validacio de ciclo*/
 
        if (!"01".equals(cicloSeleccionado) && !"02".equals(cicloSeleccionado)) {
            JOptionPane.showMessageDialog(this, "Seleccione un Ciclo válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Sale del programa si no se ha seleccionado un Ciclo válido
        }
        
        
        // Obtener la selección de nombres de las materias desde los JComboBox
        String materia1 = (String) cbMateria1.getSelectedItem();
        String materia2 = (String) cbMateria2.getSelectedItem();
        String materia3 = (String) cbMateria3.getSelectedItem();
        String materia4 = (String) cbMateria4.getSelectedItem();
        String materia5 = (String) cbMateria5.getSelectedItem();

        // Verificando que todos los JComboBox de nombres de materias estén seleccionados
        if ("-Seleccione-".equals(materia1) || "-Seleccione-".equals(materia2) || "-Seleccione-".equals(materia3) || "-Seleccione-".equals(materia4) || "-Seleccione-".equals(materia5)) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia válida para todas las notas.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Sale del programa si hay JComboBox sin selección válida
        }

        //CALCULAR EL CUM
        /*VARIABLES*/
        
        String nota1Text = tfNota1.getText();
        String nota2Text = tfNota2.getText();
        String nota3Text = tfNota3.getText();
        String nota4Text = tfNota4.getText();
        String nota5Text = tfNota5.getText();

        if (nota1Text.isEmpty() || nota2Text.isEmpty() || nota3Text.isEmpty() || nota4Text.isEmpty() || nota5Text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese todas las notas.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Sale del programa si hay campos vacíos
        }

        double notaMateria1 = Double.parseDouble(nota1Text);
        double notaMateria2 = Double.parseDouble(nota2Text);
        double notaMateria3 = Double.parseDouble(nota3Text);
        double notaMateria4 = Double.parseDouble(nota4Text);
        double notaMateria5 = Double.parseDouble(nota5Text);

        // Realizando operaciones con las notas

        int uvMateria1 = Integer.parseInt((String) cbUV1.getSelectedItem());
        int uvMateria2 = Integer.parseInt((String) cbUV2.getSelectedItem());
        int uvMateria3 = Integer.parseInt((String) cbUV3.getSelectedItem());
        int uvMateria4 = Integer.parseInt((String) cbUV4.getSelectedItem());
        int uvMateria5 = Integer.parseInt((String) cbUV5.getSelectedItem());
        
        // Calculando el numerador del CUM
        double numerador = (notaMateria1 * uvMateria1) +
                           (notaMateria2 * uvMateria2) +
                           (notaMateria3 * uvMateria3) +
                           (notaMateria4 * uvMateria4) +
                           (notaMateria5 * uvMateria5);
        
        // Calcula el denominador del CUM
        int denominador = uvMateria1 + uvMateria2 + uvMateria3 + uvMateria4 + uvMateria5;

        // Calcula el CUM
        double cum = numerador / denominador;
        
        // Comprobación de aprobación o reprobación
        int aprobadas = 0;
        int reprobadas = 0;
        
        if (notaMateria1 >= 6) {
            aprobadas++;
        } else {
            reprobadas++;
        }if (notaMateria2 >= 6) {
            aprobadas++;
        } else {
            reprobadas++;
        }if (notaMateria3 >= 6) {
            aprobadas++;
        } else {
            reprobadas++;
        }if (notaMateria4 >= 6) {
            aprobadas++;
        } else {
            reprobadas++;
        }if (notaMateria5 >= 6) {
            aprobadas++;
        } else {
            reprobadas++;
        }
        
        // Mostramos el CUM con dos decimales usando FORMAT
        String formattedCum = String.format("%.2f", cum);
        
        //Este Bloque de Codigo me a Servido Unicamente para Pobrar los procesos 
        /*if(!"-1".equals(cicloActual) && !"-1".equals(Carrera)){
            JOptionPane.showMessageDialog(this, "Calculo Exitoso " + this.tfNombre.getText() + " " 
                                                                   + " su Estado Actual es de #"
                                                                   + aprobadas
                                                                   + " Materias Aprobadas y de #"
                                                                   + reprobadas
                                                                   + " Materias Reprobadas "
                                                                   + " y su Cum Actual es de " 
                                                                   + cum);                                    
        }*/
        
        // Comprobación de aprobación o reprobación
        String estadoMateria1 = notaMateria1 >= 6 ? "Aprobada" : "Reprobada";
        String estadoMateria2 = notaMateria2 >= 6 ? "Aprobada" : "Reprobada";
        String estadoMateria3 = notaMateria3 >= 6 ? "Aprobada" : "Reprobada";
        String estadoMateria4 = notaMateria4 >= 6 ? "Aprobada" : "Reprobada";
        String estadoMateria5 = notaMateria5 >= 6 ? "Aprobada" : "Reprobada";

        // Actualiza los JLabel con el estado de las materias
        lbEstado1.setText(estadoMateria1);
        lbEstado2.setText(estadoMateria2);
        lbEstado3.setText(estadoMateria3);
        lbEstado4.setText(estadoMateria4);
        lbEstado5.setText(estadoMateria5);
        
        
        //Actualizamos el CUM en el JTextField
        jlCum1.setText(String.format("%.2f", cum));
        
        //Actualizamos la Banda de Abajo con los Datos 
        String Nombre = tfNombre.getText();//Obtenemos el Valor del TextField
        jlNombre2.setText(Nombre);//Actualiza el texto
        jlCarrera2.setText(carreraSelec);
        String aprobadasText = Integer.toString(aprobadas);// Convierte el número a una cadena (String)
        jLabel9.setText(aprobadasText);
        String reprobadasText = Integer.toString(aprobadas);// Convierte el número a una cadena (String)
        jLabel9.setText(reprobadasText);
        jLabel13.setText(String.format("%.2f", cum));
        

        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jCalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbCiclo;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUV1;
    private javax.swing.JComboBox<String> cbUV2;
    private javax.swing.JComboBox<String> cbUV3;
    private javax.swing.JComboBox<String> cbUV4;
    private javax.swing.JComboBox<String> cbUV5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlCarrera;
    private javax.swing.JLabel jlCarrera1;
    private javax.swing.JLabel jlCarrera2;
    private javax.swing.JLabel jlCarrera3;
    private javax.swing.JLabel jlCiclo;
    private javax.swing.JLabel jlCum;
    private javax.swing.JLabel jlCum1;
    private javax.swing.JLabel jlMateria;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombre1;
    private javax.swing.JLabel jlNombre2;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbEstado2;
    private javax.swing.JLabel lbEstado3;
    private javax.swing.JLabel lbEstado4;
    private javax.swing.JLabel lbEstado5;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota2;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    private javax.swing.JTextField tfNota5;
    // End of variables declaration//GEN-END:variables
}
